server:
  port: 10020
spring:
  application:
    name: cloud-feign
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000